### ISSUE TITLE
Mixed up fact order in catchup phase 1, if more than 1000 facts are waiting

### ISSUE THREAD

**Issue by dibimer** [factcast/factcast#1002]
**Describe the bug**
Upon restart of client application errors in processing of facts occur because of missing facts in catchup (e.g. "updated event" fails because "created event" has not been retrieved from database by factcast)

**FactCast Server/Client Version**
* client version: factcast-client-grpc 0.1.0
* server version: factcast-server-grpc 0.1.4.2

**To Reproduce**
Unfortunately we have not been able to reliably reproduce the error scenario so far. Starting at least two instances of the client application seems to be required.

**Expected behavior**
Factcast reliably retrieves all relevant events for a subscription.

**Additional context**
We have seen in debug logs that the lower serial boundary starts to diverge at some point during catchup for different clients.

    "2020-08-26T04:35:52.214Z" | "grpc-sub#3238  fetched next page of Facts for cid=96857536, limit=1000, ser>80029 in 31ms"
    "2020-08-26T04:35:52.307Z" | "grpc-sub#3238  fetched next page of Facts for cid=96857536, limit=1000, ser>82296 in 34ms"

 vs

    "2020-08-26T04:35:57.868Z" | "grpc-sub#3239  fetched next page of Facts for cid=96857537, limit=1000, ser>80029 in 47ms"
    "2020-08-26T04:35:58.127Z" | "grpc-sub#3239  fetched next page of Facts for cid=96857537, limit=1000, ser>84170 in 123ms"

The number of prepared facts was identical however

    "grpc-sub#3239 prepared 76777 facts for cid=96857537 in 2280ms"
    "grpc-sub#3238 prepared 76777 facts for cid=96857536 in 5437ms"

See also attached log snippet (CSV format).
[missing-facts.log](https://github.com/factcast/factcast/files/5128408/missing-facts.log)

Possible cause: Postgres does not guarantee a fixed order for a result set therefore limiting an unordered result set might produce unpredictable results.
see org.factcast.store.pgsql.internal.PgConstants#SELECT_FACT_FROM_CATCHUP

Suggested solution: add "ORDER BY ser ASC" to subquery before LIMIT
```java
public static final //
String SELECT_FACT_FROM_CATCHUP = //
        "SELECT " + PROJECTION_FACT + " FROM " + //
                TABLE_FACT + " WHERE " + COLUMN_SER + //
                " IN ( " + "   SELECT " + COLUMN_SER + " FROM " + //
                TABLE_CATCHUP + "   WHERE ( " + COLUMN_CID + "=? AND " + COLUMN_SER + //
                ">? ) ORDER BY " + COLUMN_SER + " ASC LIMIT ? " + ") ORDER BY " + COLUMN_SER + " ASC";
```

**Comment by uweschaefer** [comment]
thanks for reporting, will have a look later (currently busy).
general question: particular reason for the gap in versions used on client/server?

**Comment by dibimer** [comment]
Thank you. There is no particular reason for the gap other than that the client application dependency has not been updated since the server update. Do you expect problems resulting from the gap?

**Comment by uweschaefer** [comment]
what can i say - sound analysis and solution looks plausible.
actually i am pondering for some time if this ser-copying thing is worth it anyway, but for now - i'll just follow your suggestion.
As i am currently working towards a 0.3 release scheduled for the weekend, i'll add it in there.

However, as you've been so nice to analyze this, would it makes sense for you to have it backported to a particular release?
If so, which one? 0.1.4.2? (it is fairly old, you know that, right?) :older_man:

**Comment by dibimer** [comment]
Thank you for the quick response. So far we have refrained from updating beyond 0.1.4.2 as the in memory variant of factcast has been removed after that which we heavily use in integration testing. That being said in anticipation of a new release I have tried to update to 0.2.5 and apart from problems with testcontainers/ryuk in the local setup results look promising. We would still be grateful for a backported fix so that we can make a quick release and properly schedule the upgrade.

**Comment by uweschaefer** [comment]
regarding integration testing, there is a dedicated module with a junit extension in the 0.3er release in order to run against PG/FC in a docker container, that might be worth looking at, as soon as released.

i will backport and release 0.1.4.3, stay tuned.

**Comment by uweschaefer** [comment]
@dibimer please let me know if this release fixes the problem for you:
https://repo1.maven.org/maven2/org/factcast/factcast/0.1.4.3/

**Comment by uweschaefer** [comment]
also released 0.2.5.1 containing this fix

**Comment by uweschaefer** [comment]
feel free to reopen if necessary.

**Comment by dibimer** [comment]
The fix seems to have solved the problem. We have upgraded to 0.3 and so far everything looks fine. Thanks again for the fix.

**Comment by uweschaefer** [comment]
once you're about to use the features of the 0.3, feel free to contact. I already told Stephan, i'd be happy to come over for a talk or workshop some day, if you like. (Leipzig)
