### ISSUE TITLE
Allow multiple aggIds in FactSpec

### ISSUE THREAD

**Issue by otbe** [factcast/factcast#1093]
Right now we can add as many aggIds as we want when publishing facts but on the read side we only can specifiy one aggId in a `FactSpec`. 

I think it would be nice to be able to specify multiple aggIds in a `FactSpec`

:)

**Comment by uweschaefer** [comment]
we accept PRs, you know :D

**Comment by BernhardBln** [comment]
Took a deeper look, this would be a breaking change, as the FactSpec is serialised as JSON, stuffed into a message and then deserialised on the server side. If we change aggId from single field to a list, any previous server version would throw an exception.
Needs to be reconsidered.

**Comment by uweschaefer** [comment]
you could introduce a custom deserializer on the server side to prevent this.

**Comment by BernhardBln** [comment]
You mean, that older clients work with the newer server? That is actually not the problem here, rather newer clients / older server. We just implemented integration tests to show they still work together, this would definitely break it.
