### ISSUE TITLE
Check if lock is still held in subscribed projections

### ISSUE THREAD

**Issue by BernhardBln** [factcast/factcast#1108]
**Describe the bug**
Subscribed projections typically acquire a lock at application startup and release it only when shutting down.

This can turn into a problem when using remote locks like on Redis.

Maybe before updating the projection, check if the lock is still there (how to do this in a non-expensive way?) and try resubscribing if not.

**Comment by uweschaefer** [comment]
In case of Redis this will be done with an occasional (not to limit throughput) lock.isLocked(). However, as Redis examples do not have a home in this repo yet, this issue will be closed and implemented where it is needed.
What needs to be done in FC however is the implementation of the necessary callbacks. see #1090

**Comment by uweschaefer** [comment]
reopened to track the progress for the callback
