### ISSUE TITLE
Fix param name in WhiteListFilterServiceImpl 

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#1144]
Warning:  /home/runner/work/factcast/factcast/factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/whitelistfilter/WhiteListFilterServiceImpl.kt: (27, 49) The corresponding parameter in the supertype 'WhiteListFilterService' is named 'whiteList'. This may cause problems when calling this function with named arguments.

**Comment by Umang228** [comment]
Assign me..
