### ISSUE TITLE
Allow empty commits in optimistic locking

### ISSUE THREAD

**Issue by dibimer** [factcast/factcast#1169]
We have use cases where we can not know in advance whether facts will be emitted but we still want to ensure that the andThen() part of the locked context will get executed. Currently we have implemented a workaround using a dedicated exception that has to be extracted from the AttemptAbortedException in order to indicate successful processing of the locked context. 

```
 try {
      PublishingResult publishingResult = factCast.lock(factSpecs)
              .attempt(() -> {
                  // preprocessing
                  if (factsToInsert.isEmpty()) {
                      try {
                          doAndThenStuff();
                      } catch (Exception e) {
                          throw new ExceptionAfterPublish(factsToInsert, e);
                      }
                      throw new NoFactsToPublishAttemptException(messages.size());
                  }
                  return Attempt.publish(factsToInsert)
                          .andThen(() -> {
                              doAndThenStuff();
                          });
              });
  } catch (NoFactsToPublishAttemptException e) {
      // happy path for 0 facts
  }
```
Expected behaviour
```
PublishingResult publishingResult = factCast.lock(factSpecs)
        .attempt(() -> {
            // preprocessing
            return Attempt.publish(factsToInsert)
                    .andThen(() -> {
                        doAndThenStuff();
                    });
        });
```

Suggested fix: remove isEmpty() check in org.factcast.core.lock.Attempt or provide additional Attempt.empty() which can be combined with .andThen()
```
  static IntermediatePublishResult publish(@NonNull List<Fact> factsToPublish) {
    if (factsToPublish.isEmpty())
      throw new IllegalArgumentException("List of Facts to publish must not be empty");
    return new IntermediatePublishResult(factsToPublish);
  }
```

**Comment by uweschaefer** [comment]
Thanks for bringing this up. yes, having an Attempt.empty() there sounds like a reasonable idea.
Would you like to start a PR for that?

**Comment by uweschaefer** [comment]
@dibimer i take that as a no. Will take over...

**Comment by dibimer** [comment]
@uweschaefer actually we do have a story in our backlog to work on it, but so far it has not made it into a sprint, as we are currently working on a different problem with factcast ("channel not coming back"), which have not yet understood.
So feel free to take over, any help would be appreciated.

**Comment by uweschaefer** [comment]
Hi @dibimer 

Damn, this issue took quite a while :blush: ...

Just removing the `isEmpty` check would change the behavior thus creating a subtle incompatibility. 
Added `Attempt.withoutPublication()` to explicitly declare that you do not want to publish, but still want to execute the `andThen` part. 

Also added convenience method to encapsulate that check for an empty list into `Attempt.publishUnlessEmpty` and added it to the documentation. 

Hope this helps.

**Comment by dibimer** [comment]
Hi @uweschaefer thanks for the effort, we will definitely try to use it once it has been release.
