### ISSUE TITLE
Add administrative endpoint for counting facts according to factspecs 

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#1170]
This is useful in potential UIs (for drilldown filtering for example), for administrative purposes (check if mass publishing went as expected) and maybe e2e tests involving mass data.

However, counting in PG is very expensive and we should try to make sure, this feature is not abused for programmatic puroposes.

**Comment by uweschaefer** [comment]
fyi @edthamm

**Comment by edthamm** [comment]
I would be interested in the discussion about this. Especially about what the community thinks about the abuse case.

On hurdle we could always add is an addition to the roles and permissions concept.
That would however potentially limit the use within the potential UI. I would argue that the UI is not 'special' enough to break the rules so that should not be a deal breaker.

In terms of expense, the first thing that comes to my mind would be to severely rate limit the feature or make it async and shed these operations in situations of high load. Have not thought through the usability aspect of it for all use cases though.

**Comment by uweschaefer** [comment]
I was thinking about authorization as well. Same class as enumerate*, i think. rate limiting is something that bit our bottoms already in subscribe.

**Comment by BernhardBln** [comment]
I think we have two things here, first the permission regarding the execution of an expensive count, and second, the permission to count things in certain namespaces. The latter can be tackled with the read permissions we already have.

Why the latter is important? FactSpecs have namespace, type, version, aggId, meta and filter scripts (it is unclear if scripts should also be part of this), which makes it possible to target very specific events.

If I can count for example something like "creditlimit.CreditLimitExceeded" with aggId <companyId>, a result of 1 tells me that a certain company had their credit limit exceeded, although I might not have the rights to read this kind of Events. So in my opinion, the read permissions need to be taken into account.

**Comment by BernhardBln** [comment]
Not implementing with scripts, as this cannot be done on db level

**Comment by BernhardBln** [comment]
There are two ways to count with criteria, either using count() or using statistics.

The latter could not reflect recent inserts, unless we trigger an update, but then maybe a count would be the better solution, especially as one use case was counting facts after mass publishing:

> In order to allow the PostgreSQL query planner to make reasonably informed decisions when optimizing queries, the pg_statistic data should be up-to-date for all tables used in the query. Normally the autovacuum daemon will take care of that automatically. But if a table has recently had substantial changes in its contents, you might need to do a manual ANALYZE rather than wait for autovacuum to catch up with the changes.

My suggestion: use count, only allow admins running that command, do not allow more than x (x == 2? x == 5?) counts to run in parallel.

**Comment by BernhardBln** [comment]
Made a test implementation. Stopping here until this is solved.

**Comment by uweschaefer** [comment]
to illustrate the problem (RDS, with fully cached data)

```
postgres=> select count(*) from fact where header->>'ns' = 'transportauctions';
  count   
----------
 53112969
(1 row)

Time: 40610,819 ms (00:40,611)
          ^^^^^^^^^^^^^^

postgres=> select count_estimate('select 1 from fact where header->>''ns'' = ''transportauctions''');
 count_estimate 
----------------
       53200770
(1 row)

Time: 24,410 ms
```

i think we should go for estimating with an option to switch to exact once the count is blow a configurable threshold (like 1000).

**Comment by uweschaefer** [comment]
#2022 added the necessary building block, endpoint still needs to be implemented

**Comment by uweschaefer** [comment]
Looks like estimated counting does not work for this usecase, closing.
