### ISSUE TITLE
Improve logging when "channel not coming back"

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#1233]
**Describe the bug**
"channel does not come back" is currently logged in error level for different reasons:
* the client cancelled the subscription
* the client exceeds the max time to process messages

At least in the CANCELLED case, this should not be error level, and the message should clearly describe what was going on.

**Comment by StephanPraetsch** [comment]
Do you mean `channel not coming back.` ? Just for sake of finding that issue.
In BlockingStreamObserver
```java
          if (!delegate.isReady() && !delegate.isCancelled()) {
            throw new TransportLayerException("channel not coming back.");
          }
```

**Comment by uweschaefer** [comment]
yes, this is meant. at that point, if the channel was cancelled, we can log it in order not to confuse cancelling clients with network errors.

**Comment by StephanPraetsch** [comment]
We are receiving this log several times the last 3 days (only) in our dev system. Currently running with 0.3.1. Do you think an upgrade to the latest 0.3.13 will help? Do we need to worry? We are unsure what that exception means. Do we have problems or are these probably false positives? As it is the dev system there might be more often strange calls to factcast...

**Comment by uweschaefer** [comment]
i'd advise you to upgrade to the latest recommended version 0.3.7 or 0.3.8 or wait a few weeks for 0.4.0 to arrive.
We had a similar experience that was caused by consumers that actively cancelled subscriptions (by throwing exceptions in apply methods or similar), you might want to look into this.
Otherwise, with this little info it is hard to suggest a solution. you can contact me via DM/Twitter from 12.4. onward. 
i am on vacation before, and wont have time for a full 2h debug session, but if there is hope that i can help in 30mins, let me know)

**Comment by StephanPraetsch** [comment]
Ok. We will try 0.3.8. You don't need to spend your precious time for such a debugging :)
But is it possible to add something to have a chance to identify the client? A source IP? Just an idea ...

**Comment by uweschaefer** [comment]
good idea. debug info is already in the subscription, including the file and linenumber of the consumer where the subscription happened. we should be able to log it there...

**Comment by StephanPraetsch** [comment]
FYI: Since 0.3.8 we do not get this log anymore but we also spotted the villain: A client that took more than (the default) 60s to consume events because it calculated stuff between the consumption of each event. And this client also stopped working. So we don't know if 0.3.8 really helped. But I guess so because the logs stopped as soon as I have deployed it to the dev system.
But furthermore since 0.3.8 the Postgres has a bit higher load and we needed to upgrade it. But only in dev system, as well ...

**Comment by uweschaefer** [comment]
Thx for the report @StephanPraetsch .

We will make the 60s tolerance for slow clients configurable. From the top of my head i have no explanation for the increased load. Do you see slow queries in the log or a massive increase in the quantity of queries?

**Comment by StephanPraetsch** [comment]
I don't see anything strange but the RAM ran out of space for the Postgres. We needed to increase from 1 GB to 2 GB. Maybe we reached a limit caused by many test events.

**Comment by uweschaefer** [comment]
LOL. i assume you can bear 2GB RAM :laughing:
