### ISSUE TITLE
[SchemaRegCli] JSON filtering (title) will be applied after Hash is calculated

### ISSUE THREAD

**Issue by otbe** [factcast/factcast#1261]
**Describe the bug**
The newly introduced filtering of the schema files (e.g. removing the title) is applied after the hash is calculated which defeats the purpose 🙃

See
https://github.com/factcast/factcast/blob/master/factcast-schema-registry-cli/src/main/kotlin/org/factcast/schema/registry/cli/registry/impl/FactcastIndexCreatorImpl.kt#L38

**Comment by samba2** [comment]
It's not a matter of simply swapping the lines. Both, the checksum calculation and removing of the title attribute rely on paths in the `Project` object. Those paths point to the schema registry _source_ which are read-only files.
The checksum calculation picks up those files in the schema registry source and calculates the hash. Similarly, the copy-with-title filter method uses the same schema registry source paths to as its input.

To fix the bug, I suggest to change the hash calculation (`IndexFileCalculator`) to operate on the output directory of the schema registry CLI after the stripped JSON schemas were written.

**Comment by uweschaefer** [comment]
go ahead...
