### ISSUE TITLE
Performance Improvement: Use StackWalker instead of new Exception()

### ISSUE THREAD

**Issue by BernhardBln** [factcast/factcast#1268]
**Describe the bug**
In `FluentSubscriptionRequest` we currently use `new Exception().getStackTrace()` to get the stack trace for debugging purposes, which is very slow.

Use StackWalker instead to increase performance: https://stackoverflow.com/questions/2347828/how-expensive-is-thread-getstacktrace/49091729#49091729

Also check if performance can be increased further by introducing something like a global `debugDisabled` flag.

**Comment by uweschaefer** [comment]
The Stackwalker improvement is currently blocked, until we get to java > 8.
A general client side switch might be a good idea for people that request many tiny streams instead of using longer lasting subscriptions (which should be avoided for obvious reasons)

**Comment by uweschaefer** [comment]
thx for raising this, @BernhardBln

**Comment by uweschaefer** [comment]
thinking about it, maybe we could switch strategies at runtime so that we don't force the user to use java >8 but make use of it, if we can.

**Comment by uweschaefer** [comment]
should be easy to add now that we're on 17

**Comment by uweschaefer** [comment]
not huge though... (1mio executions)
![image](https://github.com/factcast/factcast/assets/546815/924e9eed-a51d-4785-a7a1-42f21e3f6c70)

**Comment by uweschaefer** [comment]
gee, forgot it is client side, and we're on 8 here :laughing:

**Comment by uweschaefer** [comment]
I think the performance improvement does not justify a second strategy. This might be relevant again, when we move the client to 11 or 17.
