### ISSUE TITLE
Factus: Dispatcher complains if version in @HandlerFor not set

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#1290]
**Describe the bug**
The dispatcher complains about unexpected coordinates where @HandlerFor defines only ns and type.
a version of 0 (the default) means "i do not care", so that the version should be taken out of comparison in this case.

**Comment by Umang228** [comment]
Assign this to me....and plz give a bit more specific info

**Comment by uweschaefer** [comment]
This is about the class org.factcast.factus.projector.DefaultProjector

DefaultProjector::apply is called whenever a fact was transferred from the factcast server. Now the dispatcher is retrieved from the dispatchInfo wich is buildt up when initially analyzing the projection class.

In a situation where @HandlerFor is used, and the version is not set (or set to 0) the factcoordinates in the Fact f can be different (say version 3). In this situation an exception is thrown in line 84.

Hope this helps to get you started.

**Comment by Umang228** [comment]
Plz...merge the PR#1300

**Comment by uweschaefer** [comment]
Thanks, but the code does not even compile.
