### ISSUE TITLE
Engrave Fact Versions

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#1294]
**Is your feature request related to a problem? Please describe.**
Once you have a lot of transformed Facts, the throughput is going to suffer due to the n+1 query problem, because fetching them involves a lookup in the transformationCache.

It'd be nice to mitigate this. One way to do this is to "engrave" the transformed Facts

**Describe the solution you'd like**

* move the originally published Facts that are superseeded by the version to engrave to a separate table.
* move the engraved version to the fact table

while this mitigates the latency penalty for the consumer requesting the 'engraved' version, it now introduces the same penalty for consumers that request the original version. Given that at some point in time most consumers will be updated to a particular version, this will make sense by making it fast for 90% of the consumers, plus removing considerable load from the database.

We should slightly change the semantics of requesting version 0 to be "the engraved one" rather than "the originally published one".
Obviously we'd need another special value '-1' for the original one.

**Describe alternatives you've considered**
maybe we could inspect solving the problem in the database - if you have any idea how to do that efficiently, please comment here.

**Comment by BernhardBln** [comment]
See here for some ingestion performance measures: https://github.com/factcast/factcast/issues/1558

**Comment by uweschaefer** [comment]
So unless the difference in load on the postgres database during fetching single Facts from  the Transformationcache, there currently is no pressing need to engrave versions as the read performance (4.2s vs 4.4s) is dominated by network rather than reading the facts from the database.

**Comment by BernhardBln** [comment]
The solution in #1563 will work better in general settings with clients asking for all kind of events, or teams not willing to spend time on increasing fact versions on a regular basis.

In more specialised environments and teams that want to take that burden for the sake of performance, this could still be interesting.

**Comment by uweschaefer** [comment]
closing it for now
