### ISSUE TITLE
Add scheduled check for invalid indices

### ISSUE THREAD

**Issue by otbe** [factcast/factcast#1454]
In https://github.com/factcast/factcast/pull/1437 we introduced a view on our indices. It would be good idea to have a scheduled check for invalid tail indices somewhere in the server side. 

Naive implementation could be:
- look every X minutes (something like 30 or 60)
- if something is invalid log an error

Using an actuator health check would be possible too but would lead to many error logs (depending on configuration) or it would bring the FC service down if the health check indicates an error.

**Comment by uweschaefer** [comment]
as we already have a check with a configurable interval, we might also just hook into this one...

**Comment by uweschaefer** [comment]
OTOH, if tail management is disabled, it would still be useful to have this check.
