### ISSUE TITLE
Upgrade to more recent postgres version

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#1483]
currently using 11.5. We'd need to make sure that more recent versions work as expected.

**Comment by bedaka** [comment]
Will try to move 15.2 (latest supported by RDS)

**Comment by mweirauch** [comment]
Any recently released (2023-03) minor of PostgreSQL is affected. We trapped into this with `13.10`. Unfortunately that liquibase issue didn't get much traction, yet.

(Sorry for not creating the ticket when you asked for Uwe. Life's kinda busy over here.)

**Comment by bedaka** [comment]
In this case we'll pause this issue to see if they can come up with a solution.

**Comment by otbe** [comment]
I started working on a workaround for the liquibase issue and some other minor fixes for PG15 compatibility. Stay tuned 🥳
