### ISSUE TITLE
Ingestion Performance Improvement

### ISSUE THREAD

**Issue by BernhardBln** [factcast/factcast#1558]
Using this ticket to document some performance measurements.

**Comment by BernhardBln** [comment]
### First measurement

Setup:

- Measuring on 16" MBP 2019 
- On commit 1a61c3dd97f0479e0ead3190e683ede2fc5f4fce 
- factcast-example-server with Postgres in Docker
- factcast-example-client-spring-boot-2, creating 150 000 UserCreated events

Measurement:

- fc.subscribe( v1 ).awaitCatchup() took 4.2 seconds
- fc.subscribe( v2 ).awaitCatchup() took 13.5 seconds (transformationCache was empty)
- again fc.subscribe( v2 ).awaitCatchup() took 4.4 seconds

What in fact took a long time was publishing events (3 minutes per 100 000 events), even using batches of 10 000 items.

Result:

Fetching events in a different version took 3 times the time (but was still very fast), and once the transformed events are in the transformation cache, it takes more or less the same time than reading the original events.

**Comment by BernhardBln** [comment]
Disabling schema validation (by not setting schemaRegistryUrl) still required 2:50 minutes for 100 000 events.

**Comment by BernhardBln** [comment]
Disabling the notifications including header parsing: 275 seconds for 150 000 events.

**Comment by BernhardBln** [comment]
Combining disabling notifications and schema validation: 262 seconds

**Comment by BernhardBln** [comment]
Insertion of facts is fast, but adding the serial number to the headers takes 10-20 seconds per 10 000 events.

**Comment by uweschaefer** [comment]
We should measure how much it would help to move the update (add serial and timestamp) to a trigger.
