### ISSUE TITLE
Improve performance during catchup for transformed events

### ISSUE THREAD

**Issue by BernhardBln** [factcast/factcast#1563]
**Is your feature request related to a problem? Please describe.**
Currently subscription requests for fact versions that are different than the original, published fact are slow.

Either they need to be transformed using javascript, or they need to be read (one by one) from the `transformationcache` table.

**Describe the solution you'd like**
For a subscription, we fetch `factcast.store.page-size` many records from the database at once. 

Identify from those records the ones that need transformation, and concurrently (and with a single call to the database) look them up from the `transformationcache`, with a javascript transformation as fallback.

The advantage of this solution is that 

- we do not make a single call to the database for each missing fact version, but one to fetch all missing ones in the current batch
- we can look up / transform the missing versions in parallel while the client is processing facts, making good use of the client's processing time

**Describe alternatives you've considered**
There was the suggestion to engrave fact versions (https://github.com/factcast/factcast/issues/1294) but in many scenarios there will not be _the_ perfect choice for a version, and it will require teams to constantly touch old and working code to upgrade event versions.

**Additional context**
See measurements from https://github.com/factcast/factcast/issues/1294, serving transformed facts almost took 66 times longer.

**Comment by uweschaefer** [comment]
reopening
