### ISSUE TITLE
Config free PLAINTEXT_UPGRADE connection  for client running agains a factcast server in integration test mode

### ISSUE THREAD

**Issue by samba2** [factcast/factcast#1610]
When integration testing, currently an "application.properties" file is required which configures the connect type to be plain text (`grpc.client.factstore.negotiationType=PLAINTEXT`)

Ideally, this file would not be necessary and client and server  (server in in test-mode) establish a plaintext connection automatically.

**Comment by uweschaefer** [comment]
closed as just convenience
