### ISSUE TITLE
Modified data on RTransaction's is not visible within multiple handlers

### ISSUE THREAD

**Issue by otbe** [factcast/factcast#1619]
if you call `getSet` multiple times

I guess its not a bug in `factcast-factus-redis` itself its more about a general issue how `RTransaction`s work internally.

**Comment by uweschaefer** [comment]
will be fixed by https://github.com/redisson/redisson/issues/3862

**Comment by uweschaefer** [comment]
does not look like being fixed in reddison too soon. we should consider a local fix for it.

**Comment by uweschaefer** [comment]
fixed in redisson by now
