### ISSUE TITLE
Make SnapshotSerializerSupplier take a list of SnapshotSerializer's to be able to use beans with non default constructor

### ISSUE THREAD

**Issue by otbe** [factcast/factcast#1633]
Right now we are only able to use
```
@SerializeUsing(SnapSer.class)
```

with classes that have a no-arg constructor but this is not strictly necessary 🤔

**Comment by BernhardBln** [comment]
@otbe I assume it is fine to pick the first match where we either have a default constructor, or we find it in the list? Or you had other priorities in mind?

**Comment by BernhardBln** [comment]
And what to do if none match (e.g. all Serialisers are beans, but not found in the list), throw some exception? If yes, which?

**Comment by BernhardBln** [comment]
Current state: There is some problem and we wait for feedback on that before proceeding, see https://github.com/factcast/factcast/pull/1668#issuecomment-956281582
