### ISSUE TITLE
Use production sql schema for integration tests

### ISSUE THREAD

**Issue by BernhardBln** [factcast/factcast#1670]
In #1590 we created an integration test which tests a trigger that is installed via liquibase.

Unfortunately, we do not test the SQL that is actually used in production, but a test schema which is a copy.

If the production SQL would be broken, the test would still be green, while an error would only be seen when factcast actually gets deployed somewhere.

What was the reason for this separation? Can we use the production sql schema installed by liquibase for integration tests?

**Comment by uweschaefer** [comment]
tests use liquibase now
