### ISSUE TITLE
Tail indexes not being used (every time)

### ISSUE THREAD

**Issue by otbe** [factcast/factcast#1746]
We found some long running queries in our db logs which indicate that tail indexes are not being used every time.

After some tests we might have to introduce composite tail indexes based on ser and header

```
CREATE EXTENSION btree_gin;
CREATE INDEX CONCURRENTLY idx_fact_tail_XXX ON public.fact USING gin (ser, header jsonb_path_ops) WHERE (ser > 49138983)
```

**Comment by uweschaefer** [comment]
Hard to reproduce
