### ISSUE TITLE
LocalSubscribedProjection's writer token is not unlocked on subscription.close()

### ISSUE THREAD

**Issue by maciekpapiez** [factcast/factcast#1834]
**Describe the bug**
During integration testing, we fill Factcast with events, execute a test case against it, empty the event store and execute another test case. Between the tests, we close the LocalSubscribedProjection, empty its state and resubscribe it. However, this fails as LocalSubscribedProjection's writer token is not unlocked on subscription.close() and it can't re-subscribe.

**FactCast Server/Client Version**
0.4.x

**To Reproduce**
Run a local subscribed projection, close it and attempt to subscribe it again from a new thread. This will hang. Unfortunately, I don't have a failing test case at hand - should you need one, please let me know.

**Expected behavior**
Resubscribing succeeds.

**Additional context**
the writer token that is acquired [here](https://github.com/factcast/factcast/blob/master/factcast-factus/src/main/java/org/factcast/factus/FactusImpl.java#L163):
```java
      WriterToken token = subscribedProjection.acquireWriteToken(interval);
      if (token != null) {
        log.info("Acquired writer token for {}", subscribedProjection.getClass());
        Subscription subscription = doSubscribe(subscribedProjection, token);
        // close token & subscription on shutdown
        managedObjects.add(
            new AutoCloseable() {
              @Override
              public void close() {
                tryClose(subscription);
                tryClose(token);
              }

              private void tryClose(AutoCloseable c) {
                try {
                  c.close();
                } catch (Exception ignore) {
                  // intentional
                }
              }
            });

        // ...
```

is only closed via managedObjects on application shutdown. This means that even if we have:

- a LocalSubscribedProjection
- clearing Redis/Factcast
- clearing memory state
- subscription closing in afterEach/subscribing in beforeEach

we are unable to actually subscribe it in the following test, since the token is released only on shutdown.

**Comment by uweschaefer** [comment]
somewhat loosely connected to #1817

**Comment by uweschaefer** [comment]
Hi @maciekpapiez 

could you provide a failing test?

**Comment by uweschaefer** [comment]
Can be reopened, once a failing test is available.
