### ISSUE TITLE
"RESTART IDENTITY" changes test behaviour

### ISSUE THREAD

**Issue by skynetsonar** [factcast/factcast#2013]
**Describe the bug**
After upgrading to factcast version 0.5.5 (relevant submodule is factcast-test) we experienced failing integration tests. Single test cases are ok but when running multiple in a test class only the first test passes.
Our analysis shows that when removing `RESTART IDENTITY` from *org.factcast.test.BaseIntegrationTestExtension* with 0.5.6-SNAPSHOT fixes the tests again.

The test setup is as follows:
* Spring boot integration test
  * `@SpringBootTest(classes = TestFactCastApplication.class, webEnvironment = SpringBootTest.WebEnvironment.NONE)`
  * `@Testcontainers`
  * `@FactcastTestConfig(factcastVersion = "0.5.5")`
  * `@ExtendWith({ FactCastExtension.class })`
* on startup an EventsObserver class is instantiated as PushReadModel `implements org.factcast.core.subscription.observer.FactObserver`
  * which creates a follow subscription on startup `SubscriptionRequest.follow(factsOfInterest).fromScratch()`

The follow subscription apparently does not handle the reset of the event counter in Postgres DB and therefore does not get the new events in subsequent test cases. This has been confirmed by publishing random events in test case setup bringing the counter back to where it was before the `beforeEach` cleanup.
Facts are always published using `org.factcast.core.FactCast#publish(org.factcast.core.Fact)`.

**FactCast Server/Client Version**

|Server | Client | tests ok |
|-----|-----|----|
|0.3.7 | 0.5.5 |  yes|
|0.3.9 | 0.5.5 |  yes|
|0.4.0 | 0.5.5 | no|
|0.4.6.1 | 0.5.5 |  no|
|0.5.5 | 0.5.5 |  no|
|0.5.5 | 0.5.4 |  yes|
|0.5.4 | 0.5.5 |  no|

**To Reproduce**
We unsuccessfully tried to adapt a test case like `org.factcast.itests.factus.FactusClientTest` to create a similar setup.

**Expected behavior**
Is the `RESTART IDENTITY` really necessary? If so, are we missing anything in our test setup to set back the subscription?

**Additional context**
Using `@DirtiesContext(classMode = ClassMode.BEFORE_EACH_TEST_METHOD)` is not really an option as spring context creation currently takes about 10s and occurs before Postgres cleanup so the events from the previous test case are still consumed.

Please let us know if we should provide additional details.

**Comment by uweschaefer** [comment]
Hi.. Thanks for the extensive report.

Do you close your subscription after the test before resubscribing in the new ones?

**Comment by uweschaefer** [comment]
to elaborate a bit: RESTART IDENTITY resets the serials of the fact table. this is useful in order to have (for instance) reproduce-able serials in tests. Serials also define a before/after relation between events, so that it is not expected to receive serials like "3,4,5,6, - reset and move to next test - 0,1". 
I think closing subscriptions and not reusing them across tests should be the way to go. Please let us know if it helps.
