### ISSUE TITLE
Revert dependency to Redisson

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#2030]
Versions after 3.17.x have failed for us due to stability problems. Until we have more insight, we'll revert to the latest "known good" version.

**Comment by uweschaefer** [comment]
see https://github.com/redisson/redisson/issues/4299

**Comment by otbe** [comment]
3.17.x is the faulty version range. 3.16.8 seems to be stable for us

**Comment by uweschaefer** [comment]
Looks like the observed problem was caused by a provisioning problem unrelated to the version used.
