### ISSUE TITLE
Generate Actions yml via Kotlin DSL

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#2037]

**Comment by krzema12** [comment]
Hi @uweschaefer, author of github-actions-kotlin-dsl here, just noticed you use it - cool, happy to see it :)

FYI, in most recent version 0.19.0 it's possible to regenerate the workflow from any directory. This piece won't be needed anymore

https://github.com/factcast/factcast/blob/36877e95d3046efc4b23d417cf7d2d7851153332/.github/workflows/format.main.kts#L59-L60

and you'll have to pass

```kotlin
sourceFile = __FILE__.toPath()
```

See the example on https://krzema12.github.io/github-actions-kotlin-dsl/user-guide/getting_started/.

Cheers!

**Comment by uweschaefer** [comment]
Thanks for mentioning @krzema12 - will test that asap.

Keep up the impressive work. Using the DSL was a breeze! 
(However 'corretto' was missing as a JDK flavor, maybe you want to add it).

**Comment by krzema12** [comment]
Thanks!
Sure thing, I'll add Corretto: https://github.com/krzema12/github-actions-kotlin-dsl/issues/293
Feel free to also create a ticket for actions for which you had to use the CustomAction.

**Comment by krzema12** [comment]
Here: https://github.com/krzema12/github-actions-kotlin-dsl/issues/294

BTW, did you use the script generator (converter from YAML to Kotlin script), or wrote the script from scratch?

**Comment by uweschaefer** [comment]
generator to start with.

**Comment by uweschaefer** [comment]
relying for quite some time now on the DSL. Thanks again to @krzema12 and congrats to the success of that project!
