### ISSUE TITLE
Factus.update call stuck indefinitely after a manual intervention in the DB

### ISSUE THREAD

**Issue by JanM-cz** [factcast/factcast#2162]
**Describe the bug**
We observed a deadlock during operation of factcast clients. The issue seems to be somehow related to exception handling in Factus.update() method. The issue popped up during a manual factcast DB intervention, which rendered the server unable to handle the client calls appropriately.

**FactCast Server/Client Version**
Client version 0.6.1

**To Reproduce**
No exact steps to reproduce known.

**Expected behavior**
An exception is thrown by the Factus.update() instead of blocking forever.

**Comment by otbe** [comment]
What we observed so far:
`factus.update` gets stuck (blocks forever) when the server keeps returning error responses.
In theory every sync call (update, publish..) should throw exceptions whenever a non-communication (these are retried) related error happens.

**Comment by otbe** [comment]
@JanM-cz was it in an integration test scenario where this first occurred?

**Comment by JanM-cz** [comment]
@otbe we were not able to reproduce it in an integration test scenario, happened on ent (real execution) environment.

**Comment by otbe** [comment]
Okay thanks. We tracked down an issue where something like this can be caused in an integration test scenario. Then lets keep this open :)
