### ISSUE TITLE
Add reason column to event blacklist table.

### ISSUE THREAD

**Issue by bedaka** [factcast/factcast#2180]
At the moment the blacklist to permanently ignore events only consists of one column containing the event id. This will make it hard to understand why events where blacklisted in the past. 

Therefore a (mandatory) `reason` column could be added where information regarding the reason for blacklisting and the type of the event can be documented.

I would refrain from adding multiple fields (type, reason, ...) as the blacklisting process should be fast and intuitive since it might be used in an emergency scenario.

**Comment by uweschaefer** [comment]
closed by #2292
