### ISSUE TITLE
Testcontainers with disabledWithoutDocker - Why?

### ISSUE THREAD

**Issue by StephanPraetsch** [factcast/factcast#2202]
Hi,

why did you set
```
@Testcontainers(disabledWithoutDocker = true)
```
[here](https://github.com/factcast/factcast/blob/6ef5919547e1cb451ea45cd5f8f98181ca61ef2f/factcast-test/src/main/java/org/factcast/test/AbstractFactCastIntegrationTest.java)? What is the reason? We always have docker running. Most likely because of that our maven jobs (and Gitlab jobs) were green without executing any tests. Took awhile to spot this.

I really like to not use this configuration.

**Comment by uweschaefer** [comment]
Call me crazy, but you cannot use testcontainers without docker, so that you just cannot execute test that rely on testcontainers.
Where am i wrong?

There are some execution environments, where you just cannot execute docker.

**Comment by StephanPraetsch** [comment]
But it's part of a AbstractFactCast**Integration**Test. I expect then a real factcast to be started (via testcontainers).

**Comment by uweschaefer** [comment]
I must be missing something, but for me it seems pretty plausible that you cannot use testcontainers without docker.

**Comment by StephanPraetsch** [comment]
In other words: My expaction on an abstract factcast **integration** test class is that it integrates a factcast. How else can a factcast be integrated if not via testcontainers and docker? I remember the removed in memory factcast. Is there something similar then?
Otherwise I expect this class to throw an exception if it cannot provide me a factcast.

**Comment by uweschaefer** [comment]
As i said earlier, it might be reasonable to have one testsuite and execute the possible parts in different environments. breaking the build where docker is unavailable is probably not going to make friends.
If you want to break your build if testconatiners does not work in a particular environment, it can easily be done with a single test that fails in that situation.

**Comment by uweschaefer** [comment]
Why don't you just subclass and override?

**Comment by uweschaefer** [comment]
About the inmem mock store: we removed it, because it was next to impossible to keep the behaviour in sync with the pgstore. In order to gain confidence on integration tests, we went for the testcontainers based approach. There is no other mock store and we decided there shouldn't be any.

**Comment by StephanPraetsch** [comment]
Well, for us it's completely unexpected that an integration class for providing a factcast isn't providing a factcast without any exceptions but silently ignore to start a factcast. But fine, then we have to work around.

**Comment by uweschaefer** [comment]
Why can't you provide a runnable docker on your Ci environment?

**Comment by StephanPraetsch** [comment]
We do. It was just about testing in different systems and sometimes there was no docker running - by accident. The maven job was green because no tests were executed because this silent ignore. There were actually broken tests but we didn't see this because we trusted the green maven job. We didn't check if there were no tests executed at all. This led us to a wrong debug trace.
