### ISSUE TITLE
truncate of postgres table causes open connections to be "broken"

### ISSUE THREAD

**Issue by StephanPraetsch** [factcast/factcast#2205]
Hi,

our assumption is that you introduced in 0.5.5 a [clean up](https://github.com/factcast/factcast/blob/6ef5919547e1cb451ea45cd5f8f98181ca61ef2f/factcast-test/src/main/java/org/factcast/test/BaseIntegrationTestExtension.java#L140-L152) that "breaks" open connections in follow mode.

roughly:
```
// spring boot stuff
class MyTest {
  @Inject MyPushReadModel p; // follow mode, inialized and started via SpringBoot
  @Test test1() {
    publishEvent(A)
    assertThat(p).hasReceived(A)
  }
  @Test test2() {
    publishEvent(B)
    assertThat(p).hasReceived(B)
  }
}
```
* single execution: both green
* all execution: only first test is green and second test doesn't receive any (new) events
* if you add `@DirtiesContext` then all executions are green

How do you test with follow mode in an integration test?

**Comment by uweschaefer** [comment]
we've had this before: you have to close your subscriptions in between tests.

**Comment by uweschaefer** [comment]
I think it was Dietmar at the time. Please note that fc.subscribe(...) returns a Subscription object that is AutoClosable.

**Comment by StephanPraetsch** [comment]
thanks
