### ISSUE TITLE
Add support for additional Redisson codecs

### ISSUE THREAD

**Issue by bedaka** [factcast/factcast#2231]
(Follow-up task to https://github.com/factcast/factcast/issues/2181)

Currently we do not allow to use typed codecs for Redisson serialization, namely:

- TypedJsonJackson
- CodecCompositeCodec

as it might be interesting to use them, we could consider adding support in the RedissonSnapshot cache. To add the configuration an additional property might be necessary

**Comment by uweschaefer** [comment]
As we're only dealing with snapshots and the codec is used not to serialize the projection itself but rather a jackson serialized version with some meta-data, i don't think it'd be interesting for anyone to add a Composite Codec or something for the Snapshots but rather implement a SnapshotSerializer.

see 
https://github.com/factcast/factcast/blob/abeaffb0b96066570d72e2cfaff948ab8edb443c/factcast-factus/src/main/java/org/factcast/factus/serializer/SnapshotSerializer.java


I think we can close this one, agree @bedaka ?
