### ISSUE TITLE
Flaky test PublishDuplicateTest.descriptiveErrorOnPublishingDuplicates (v2)

### ISSUE THREAD

**Issue by otbe** [factcast/factcast#2291]
PublishDuplicateTest.descriptiveErrorOnPublishingDuplicates:58 » Retryable io.grpc.StatusRuntimeException: UNKNOWN

Link to failing job: https://github.com/factcast/factcast/actions/runs/4940374642/jobs/8831965849

**Comment by uweschaefer** [comment]
Probably connected to the system.out flushing issue we had on several occasions.

**Comment by uweschaefer** [comment]
Thesis is, if we play with toxiproxy connections to the database, factcast may or may not have broken connections in its pool after a test. For now, we're restarting the FC Server after the test, if you injected a PostgresProxy into the test class.

**Comment by uweschaefer** [comment]
closed by #2293
