### ISSUE TITLE
RedisTransactionalLens stores wrong tx manager instance

### ISSUE THREAD

**Issue by BernhardBln** [factcast/factcast#2316]
We ran into a strange exception in event handlers of transactional subscribed redis projections, when running integration tests (using a test extension that subscribes subscriptions on demand, per test):

> Unable to execute operation. Transaction is in finished state!

The error comes when trying to obtain a redis map or set from the given RTransaction.

The reason is apparently that the RedisTransactionalLens keeps a copy of the txManager when created.

In our test setup (not sure if its the same in general) the lenses for **all** projections are created on the same thread, the one that also discovers event handler methods.

And because of this they all share **the same** transaction manager, and when the subscription happens after (on different threads per projection with dedicated tx managers per projection), the lenses will still use the shared transaction manager from above.

Worse, the abstract redis projections use the dedicated txManager for the subscription thread, so the event handlers get the shared tx manager injected (and change their data there), but the update to the state is happening on the individual tx managers.

**FactCast Server/Client Version**

Latest.

**To Reproduce**

Create two redis subscribed projections. You most likely run into that error (but it depends on concurrency, if you don't see it try multiple times)

**Expected behavior**
We don't run into `Unable to execute operation. Transaction is in finished state!` when getting redis maps or sets from the RTransaction.

**Comment by uweschaefer** [comment]
just rechecked the redissons behavior:

```java

  public static void main(String[] args) {

    Config config = new Config();
    config.useSingleServer().setAddress("redis://127.0.0.1:6379");
    RedissonClient client = Redisson.create(config);

    // different TX, even from the same thread

    client.getBucket("bar").set(1);

    var t1 = client.createTransaction(TransactionOptions.defaults());
    var t2 = client.createTransaction(TransactionOptions.defaults());

    System.out.println(t1 == t2); // false

    // Same bucket within one transaction

    var b1 = t1.getBucket("foo");
    var b2 = t1.getBucket("foo");

    System.out.println(b1 == b2); // true

    // different buckets from different TX

    var ti2 = t2.getBucket("foo");

    System.out.println(b1 == ti2); // false

    // Same bucket within one transaction, even though there are different codecs used !!! Fist one
    // will be used [BROKEN]

    var x1 = t1.getBucket("broken", UUIDCodec.INSTANCE);
    var x2 = t1.getBucket("broken", JsonJacksonCodec.INSTANCE);

    System.out.println(x1 == x2); // true [BROKEN]

    x2.set(UUID.randomUUID());
    var uuid = x1.get();

    System.out.println(uuid); // [BROKEN] uses UUIDCodec

    t1.commit();
    client.shutdown();
  }
```

**Comment by uweschaefer** [comment]
https://github.com/redisson/redisson/issues/5127
