### ISSUE TITLE
Multiple typos and small issues in the documentation

### ISSUE THREAD

**Issue by papacito** [factcast/factcast#2331]
There are multiple small issues in the documentation of the FactCast
* typos
* missing commas
* wrongly formatted tables
* grammatical issues
* capital/small letter issues
* missing hyphens

**Comment by papacito** [comment]
PR: https://github.com/factcast/factcast/pull/2332

**Comment by papacito** [comment]
@uweschaefer This issue can be closed now, since the PR was just merged. I bet it needs some proper labels or versions to be set.

**Comment by uweschaefer** [comment]
if you add a "closes #xyz" comment to the PR it'll close the mentioned issue on merge.
