### ISSUE TITLE
Notify when Redis Transaction got committed

### ISSUE THREAD

**Issue by BernhardBln** [factcast/factcast#2342]
**Is your feature request related to a problem? Please describe.**
In @RedisTransactional projections, we need to know when the transaction got committed, in order to rebuild some caches. 

**Describe the solution you'd like**
I'd like to have an interface that I can implement in `@RedisTransactional` annotated projections, that gives me `onCommit()` and `onRollback()` handlers.

**Describe alternatives you've considered**
Currently we do this via a subscription on the state bucket, relying on some internal information like the name of the bucket, which is a bit dangerous. Also it requires the server to have a specific notify-keyspace-events configuration for it to work.

**Comment by uweschaefer** [comment]
basically impossible to generalize. also it poses very many questions about the lifecycle in which those notification should or should not be delivered.
As this can be done easily within the service, for now we conclude to not change factus for it.
