### ISSUE TITLE
"Redisson already shut down" error messages on app shutdown

### ISSUE THREAD

**Issue by BernhardBln** [factcast/factcast#2381]
**Describe the bug**
We see a lot of error messages in the log when an application is gracefully shut down, that redisson is already shut down.

Most likely because factus has an implicit dependency on redisson: The bean container is not aware of that dependency, but factus keeps a couple of resources (that are not beans) that will be closed upon destruction of factcast, and some of those resources require redisson to stay active until they got closed.

**FactCast Server/Client Version**
0.6.9

**To Reproduce**
Difficult, as it is a bit random, but happens usually on AWS / ECS when redeploying

**Expected behavior**
No error messages any more, as redisson is only shut down after all resources that depend on it got shut down before.

**Comment by uweschaefer** [comment]
thx for the initial impl. i took the liberty of generalizing this a bit, so that there is no direct dependency.
