### ISSUE TITLE
Fix flaky SubscriptionReconnectionITest

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#2484]
**Describe the bug**
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.807 s -- in org.factcast.itests.factus.lock.StateTokenTest_Latest
[INFO] 
[INFO] Results:
[INFO] 
Error:  Failures: 
Error:    SubscriptionReconnectionITest.subscribeWithFailingReconnect:155 
Expecting code to raise a throwable.
[INFO] 
Error:  Tests run: 100, Failures: 1, Errors: 0, Skipped: 0

**FactCast Server/Client Version**
0.7.0-RC

**To Reproduce**
https://github.com/factcast/factcast/actions/runs/6417741029/job/17424111193?pr=2334

**Comment by leflamm** [comment]
new PR: https://github.com/factcast/factcast/pull/2487
