### ISSUE TITLE
Handshake on GRPC failover

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#2578]
**Describe the bug**
When a client fails over to another server, there currently is no new handshake, which is a problem as the server config can be different from the original server (protocol version, compression etc), so that the handshake has to happen for a fresh start of communication to the new server.

**Comment by bedaka** [comment]
This can be tested by deploying the server and verifying if there are handshake logs from the client.

Place for change is within the reconnect logic. 

somewhere in:
ResilientGrpcSubscription
