### ISSUE TITLE
[Server UI] Add property to control source for store enumeration 

### ISSUE THREAD

**Issue by otbe** [factcast/factcast#2757]
In order to use event namespaces and types from the (pg) factstore directly rather than from the schema registry we need to be able to control this behaviour even if a schema registry is configured.

Use case:
You want to be able to filter for not yet exisitng the schema registry (but published) event types in the Server UI "Query" view.

Suggestions for property:
factcast.store.enumeration-direct-mode (default: false)

To be considered in `org.factcast.store.internal.PgFactStore#enumerateNamespaces` and `org.factcast.store.internal.PgFactStore#enumerateTypes`

**Comment by uweschaefer** [comment]
closed by #2758
