### ISSUE TITLE
Remove snapshotCache from factstore API

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#2884]
followup on #2880 

We need to provide a default (not for production use) instead

**Comment by bedaka** [comment]
What is the idea for the default? Client side in-memory?

**Comment by mamup11** [comment]
For now at least Im going to set the default for Client side in-memory

**Comment by uweschaefer** [comment]
to survive restarts, we could offer something similar to 
https://www.javacodegeeks.com/2013/12/extending-guava-caches-to-overflow-to-disk.html

**Comment by mamup11** [comment]
Good idea! Although many services run in read only containers or with not persistent volume attached, but still seems like a reasonable default

**Comment by uweschaefer** [comment]
in-mem is a fine default, doing persistence this way is probably just for playing around on the local laptop.
