### ISSUE TITLE
Flaky Test GrpcStoreResilienceITest.testConcurrentRetryBehaviorWithoutResponse

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#2911]
![image](https://github.com/factcast/factcast/assets/546815/fd6871aa-1ba0-41c4-8f55-a6be8f4b6f23)

https://github.com/factcast/factcast/actions/runs/9162128564/job/25188479175

**Comment by bedaka** [comment]
closing this since PR was merged
