### ISSUE TITLE
Snapshot deployment fails because of missing prefix 

### ISSUE THREAD

**Issue by bedaka** [factcast/factcast#2941]
since maven-plugin-plugin version 3.13.1 snapshot deployments fail in the factcast-schema-registry-maven-plugin because of a missing prefix. 

This can be surpassed by rolling back the maven-plugin-plugin to 3.12.0

**Comment by bedaka** [comment]
https://issues.apache.org/jira/browse/MPLUGIN-524

**Comment by uweschaefer** [comment]
closed with 0.7.8
