### ISSUE TITLE
Flaky Test: ClientWithSeparateCredentialsTest.failsToCatchup 

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#2949]
**Describe the bug**

https://github.com/factcast/factcast/actions/runs/9374545904/job/25810816870?pr=2915

or

https://github.com/factcast/factcast/actions/runs/9560351921/job/26352321252?pr=2964

**Comment by leflamm** [comment]
some progress... at least reproducible now:

In `ClientWithSeparateCredentialsTest` comment-out all test methods other than `failsToCatchup` and run via 

```bash
~/git/hub/factcast/factcast-itests/factcast-itests-security$ mvn clean -DskipUnitTests verify -Dit.test=ClientWithSeparateCredentialsTest 
```
This fails every time (on my machine :-/)

Weird, though:
* does not fail in Idea
* does not fail if other tests are `@Ignore`d

**Comment by leflamm** [comment]
Managed to reproduce the error locally:
- it is a race condition depending on whether the `ResilientGrpcSubscription#awaitCatchup` happens before or after `ResilientGrpcSubscription#close`, also see https://github.com/factcast/factcast/pull/2968
- in the 'after' case a generic `SubscriptionClosedException` hides the actual error-causing Throwable, here: `StatusRuntimeException` expressing `PERMISSION_DENIED`
- provided solution: remember the error-causing Throwable and re-throw it in this situation, wipe that Throwable in case of a successful reconnect
