### ISSUE TITLE
0.1.4 contains SLF4J-API classes

### ISSUE THREAD

**Issue by C-Otto** [factcast/factcast#496]
When importing factcast-core 0.1.4 via Maven the corresponding JAR file contains org.slf4j.MDC (and other classes from slf4j-api). Instead of providing the classes, I expect slf4j-api to be referenced using Maven.

**Comment by C-Otto** [comment]
Related to maven-shade-plugin (46bc596827b6f83129cddd95485aa7294073da23 and following)

**Comment by uweschaefer** [comment]
confirmed
