### ISSUE TITLE
Detach from mercateo oss parent pom

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#503]
Things would be much easier, when factcast would not have any parent pom, so that plugins won't interfere (license for instance) with their parent counterparts. as the parent pom is not expected to be maintained, it'd be simpler to just include what is needed into factcast/pom.xml directly.

**Comment by mweirauch** [comment]
Or use 'basepom-oss' from the basepom project. I can't complain, as it sets up all the magic and has toggles for disabling things you are not interested in.

**Comment by uweschaefer** [comment]
@mweirauch thanks for the pointer.

had a look at it. while it would be slightly better than the current situation, the point of this issue is to get rid of configs for disabled license plugin etc (as it is taken care of by spotless) in order to make more obvious what happens.
