### ISSUE TITLE
Improve developer experience for eclipse users

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#510]
grpc-api does only build on cmdline because of os detection not configured in eclipse.

**Comment by mweirauch** [comment]
Thx. FYI, the 'os-maven-plugin' is also an Eclipse plugin. I usually dropped it into the Eclipse plugins folder and this did also do the trick. But this is of course better.

**Comment by uweschaefer** [comment]
jup. i found out just before and was about to add that to the readme, but this way it just works(tm) :D
