### ISSUE TITLE
DDL and DML user separation doesn't work as advertised

### ISSUE THREAD

**Issue by mweirauch** [factcast/factcast#548]
**Describe the bug**
When having liquibase do the DDL with a dedicated user, the ownership of the created database resources (e.g. tables) isn't transfered to the regular DML user, so the DML user can't access these.

**FactCast Server/Client Version**
0.1.4.2 (migrated from 0.0.33)

**To Reproduce**
Migrate with two distinct users. Try to `PgFactStore::stateFor` to make use of the 'tokenstore' table. (access denied)

**Expected behavior**
The created database resources should be owned by the DML user.

One way I can think of is using the `dml-user` liquibase parameter and setting the owner afterwards in a new changelog for all created resources. For future changelogs, it might be possible to `SET role $dml-user` (unverified). But also this has it's drawbacks as the changelog hash (md5sum) is actually calculated after the statements have been interpolated from what I read. So if you ever change the dml-user param, hashes might be calculated differently.

I am scratching my head around security aspects vs. complexity of this setup.

**Additional context**
As a side-note, having a dedicated DDL user in a Spring Boot context also seems to not free the dedicated connection pool for liquibase. This should be investigated or rather hinted at, on how one can get rid of the pool when the app has performed the DDL operations.

**Comment by uweschaefer** [comment]
hmm... tricky indeed. i guess the proper solution here, is to have dedicated patches that GRANT to the dml-user that follow newly created resources.
Another way of course would be to work with wildcards...

about closing the pool - good catch! i think there is a solution to that problem. i may move that to another issue.

**Comment by uweschaefer** [comment]
looks like 
```GRANT ... on all tables ...```
means on all tables that currently exist.

maybe you are just right with the cost/benefit assesment...

**Comment by uweschaefer** [comment]
feature will be removed from factcast. #601
