### ISSUE TITLE
Drop support for Spring-boot 1

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#605]
As Spring-boot 2 is released for almost two years now, it is time to drop support for spring-boot 1, as it makes things complicated when upgrading grpc for instance.
It should still be possible to use the older client, but maybe the user needs to do some tweaking in the future, when the API evolves.

**Comment by mweirauch** [comment]
Shouldn't the `factcast-client-grpc-boot1` module have been dropped as well?

**Comment by mweirauch** [comment]
Ping ^^

**Comment by uweschaefer** [comment]
gone from master...
