### ISSUE TITLE
Drop inMem impl of FactStore 

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#607]
As the in-mem factstore diverges from the postgres implementation it looses its purpose as an alternative for tests.
Testcontainers are fast enough to provide a proper PG, so that they should be used instead.

**Comment by mweirauch** [comment]
I am not sure I like this one ...

How easily can factcast *client* projects test-double a FactCast now? As far as I remember there's no containers we build and publish during releases neither a source for that which is not based on examples. Or going crazy then and pulling in factcast-store-postgres as a test dependency and pointing this one to a Postgres TestContainer? Am I missing something? Mocking a FactStore is the advise?

**Comment by uweschaefer** [comment]
Thanks for sharing.
The point is, that the inmem store differs in behaviour already and this will probably get worse soon.
However, it is a fair point, that for testing purposes, it might be an interesting approach to have a testcontainer ready that provides a factcast with postgres in one container. 
Until then, bringing a server in as a test dependency is probably the way to go, **if** mocking the factcast client or the factstore is not what you want.

i'll create a ticket for a composite docker image module...
