### ISSUE TITLE
Add Module for integration Tests including GRPC

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#612]
In order to avoid regressions, we need a module for integration tests, that (probably using docker-compose) sets up factcast instances and a postgres in order to run tests against, that involve communication via the grpc protocol. 
Even though we can run integration tests in VM after #447 is done, they do not involve GRPC.
The GRPC layer has his own quirks (api changes over time, feeble dependencies to netty libraryies that can go wrong, etc) so that testing this automatically would be paramount.
Prerequisite for this is to revisit docker container creation.  #621

**Comment by mweirauch** [comment]
Could you be a bit more elaborate what this ticket is about? What are the ACs?

A (maven-)module within the project to perform integration tests against a stitched together factcast-server during the build or a module for use by third-party client applications testing their integration with the GRPC API?

Feel free to delete this comment afterwards.

**Comment by uweschaefer** [comment]
just a module to test different GRPC setups during build.

**Comment by uweschaefer** [comment]
needs some actual tests and scenarios for non-tls and basicauth

**Comment by uweschaefer** [comment]
closed by #623
