### ISSUE TITLE
rename store.pgsql to store and refactor properties accordingly

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#638]
as there is no other backend store than postgres any more.
It might make sense to not deprecate and transfer the older properties, but fail immediately and make the user do this conciously.

**Comment by mweirauch** [comment]
Making this hard decision sounds not only to rename properties but also renaming the module to `factcast-store` only? I mean, what is the benefit of this?
Are there any abstractions codewise which can be simplified by going the "one store only" approach? I guess the `FactStore` abstraction is to stay?
Which obstacles need to be bypassed permanently just for the sake of obliterating extensibility with other stores or another approach on the postgres implementation in a separate module?

**Comment by uweschaefer** [comment]
Trigger for this is, that i started to implement non-store specific server behaviour.
Instead of introducing another layer, i'd like to simplify things, as realisitically, we settled for postgres for persistence.
i'd like to rename module, properties etc.

for the compatibility, it is easy to support the old properties, i'll do that.

makes sense?

**Comment by mweirauch** [comment]
The renamed properties are really the easiest thing to cope with given one does a switch to a newer version.

So given it's decided that there'll be no other store, I am interested to see what structure (be it code or modules) be there afterwards and what gets simplified. So safe the property compatibility for the end ;)

**Comment by uweschaefer** [comment]
i'll give it a second thought. maybe we can implement generic server functionality by adding another store that relies on the pg store. this would add autoconfiguration complexity but may work.
i'll experiment with this on the weekend.

**Comment by otbe** [comment]
In the scope of our 0.4.0 milestone we would like to tackle this topic finally.

Target is:
- rename `factcast-store-pgsql` to `factcast-store` (and `factcast-store-pgsql-rds` accordingly)
- new config prop prefix `factcast.store`
- old properties are still supported but they are deprecated and a warning is logged
