### ISSUE TITLE
Client yields "UNAUTHENTICATED: Authentication failed" even if Factcast security is disabled

### ISSUE THREAD

**Issue by otbe** [factcast/factcast#696]
**FactCast Server/Client Version**
0.2.0-M7

**To Reproduce**
Start the example server and run
`java -jar target/fc-cli.jar --no-tls follow -ns default`

**Expected behavior**
Should print out catchup

**Additional context**
I see the warning of the factcast that securit is disabled in my logs but it seems that this is a trap 😂

**Comment by uweschaefer** [comment]
IT'S A TRAP!
