### ISSUE TITLE
Self-defense against spinning client

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#905]
In one project, a misbehaving client subscribed in an endless loop. This led to FactCasts connection pool being exhausted and finally to its health status (because of that) going to unhealty, which made a caring Loadbalancer kill it.

While this is all understandable, FactCast should try to protect itself by detecting situations like these and either throttle or even reject overwhelming subscriptions.
Any Opinions of how this should be implemented?

**Comment by mweirauch** [comment]
So - I haven't checked the implementation - does that mean that one continuous SubscriptionRequest is actually blocking one database connection?

Should some kind of throttling be handled on the application (SubscriptionRequest handling) or rather on the network layer (grpc perhaps)? The latter also requiring some knowledge then about application layer concerns like "clientId" or some other identificator if you don't want to constrain on some network level properties like remote ip:socket. Also the latter implies any other means of communication technology would need to be re-implemented for that one again.

On a quick thought a custom ServerInterceptor with bucket4j came into my mind. A quick search turned up https://github.com/Netflix/concurrency-limits.

**Comment by uweschaefer** [comment]
Hi @mweirauch 

no. a follow description consists of several queries and thane waiting for a signal via Listener/Eventbus to fetch fresh facts of interest after they have been published.
In between, the DB Connections is properly released and returned to the pool.

The only steady connection ist the one that the Listener operates on (which is outside of the pool), but this is just one per factcast SERVER, rather than client.

However, if a client requests subscriptions from scratch because when reading the first ever, due to a bug it closes and reconnects the subscription, and it does it on multiply instances, well that'll be a good reason for the connection pool to max out nevertheless, based on context parameters like the size of the pool, the cpu speed of the factcast server, latency talking to the DB, etc...

So the reason for us was a "spinning" client that went on a requesting spree due to some application level bug.

We feel like this should be possible to detect, and we added a PID to the subscription request already, in order to decide with higher confidence, that a terrorizing subscription request comes from the same client.

What we still need to agree about is the rules: For instance: 
* do we only take follow subscription requests into account?
(A high rate of catchup SRs could be just a busy application with a pull-style model)
* what is a potentially accepted rate (like 10 a second?)
* or do we just keep track of the requests, and if the (semantically) same request comes in for the n-th time, without the client progressing in the stream, this should be rejected? 
* or would we want to throttle in a way? (nice project you linked up there, i was not aware of that, but i doubt it is applicable here)
* how to communicate that back to the client / on which level? StatusRuntimeExc, or an error signal, maybe even a new kind of signal?

For any of those (and the others that i cannot think of right now) questions, as always, and form of input or suggestions would be highly appreciated and valued.

Have a nice evening.

**Comment by uweschaefer** [comment]
Thinking about it. i don't know of a database rejecting an application connecting over and over running just one (and maybe always the same) query.
