### ISSUE TITLE
Extract examples to extra project

### ISSUE THREAD

**Issue by uweschaefer** [factcast/factcast#923]
so that they are not pushed to maven central unnecessarily

**Comment by mweirauch** [comment]
Didn't I fix this a while back?

https://github.com/factcast/factcast/commit/5dbaa0be926619ef51632f5a6d98630b22331f43

**Comment by mweirauch** [comment]
The last time I was a bit active, my impression was the examples uncovered some issues at times which hadn't been covered by unit or integration tests.

**Comment by uweschaefer** [comment]
<maven.deploy.skip>true</maven.deploy.skip> does not solve the issue. it should, but doesn't.
problem is that maven deploy plugin is replaced by sonatype nexus thingy on release, so we're uploading loads of MBs to central.

this was fixed in #924 , so that we don't need to extract them anymore. Yes the examples are handy to be part of the CI/CD as modules in the same project (and they will continue to be). Just when using the ossrh profile, we'll cut them out.
